changelog:
  exclude: { labels: [skip-changelog] }
  categories:
    - { title: Breaking Changes, labels: [breaking] }
    - { title: Features, labels: [feat] }
    - { title: Fixes, labels: [fix, hotfix] }
    - { title: Other, labels: ["*"] }
